### ISSUE TITLE
Enderman error

### ISSUE THREAD

**Issue by Fargus5** [LucasRomier/BetterMobAI#3]
Hi, new error from enderman

`[17:52:04]: [WARN] [BetterMobAI] Task #13982757 for BetterMobAI v3.0.1 alpha generated an exception
java.lang.IllegalArgumentException: x not finite
at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:118) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.Location.checkFinite(Location.java:1071) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.entity.CraftEntity.teleport(CraftEntity.java:499) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.teleport(CraftLivingEntity.java:556) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.entity.CraftEntity.teleport(CraftEntity.java:493) ~[patched_1.15.2.jar:git-Paper-226]
at com.LucasRomier.BetterMobAI.Mobs.Entity.Overworld.BetterEnderman$3.run(BetterEnderman.java:100) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1240) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-226]
at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by LucasRomier** [comment]
Has been fixed. Thank you!

**Comment by Fargus5** [comment]
Hi, the error is still there

`[20:13:07]: [WARN] [BetterMobAI] Task #1910061 for BetterMobAI v3.0.1 alpha generated an exception
java.lang.IllegalArgumentException: x not finite
at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:118) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.Location.checkFinite(Location.java:1071) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.entity.CraftEntity.teleport(CraftEntity.java:499) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.teleport(CraftLivingEntity.java:556) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.entity.CraftEntity.teleport(CraftEntity.java:493) ~[patched_1.15.2.jar:git-Paper-226]
at com.LucasRomier.BetterMobAI.Mobs.Entity.Overworld.BetterEnderman$3.run(BetterEnderman.java:100) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1240) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-226]
at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by LucasRomier** [comment]
Hi, 

I'm looking into it.
Are you using the latest version?

**Comment by Fargus5** [comment]
Yes, you didn't update any new version on spigot. I'm using the latest one.

**Comment by LucasRomier** [comment]
I did, I just forgot to release it under a new version... Here's the link: https://www.spigotmc.org/resources/better-mob-ai.38166/update?update=334714

**Comment by Fargus5** [comment]
I already have this version:

Alpha 3.0.1

**Comment by Fargus5** [comment]
Ok thanks
